languages = {
	"hien" : [ "हिन्दी","Krish Yadav"],
    "enen" : [ "English","Krish Yadav"],    
    "maen" : [ "Marathi","Yash Yadav"],
	"mlen" : [ "malayalam","AUTO GENERATED"],
	"neen" : [ "nepali","AUTO GENERATED"],
	"caen" : [ "catalan","AUTO GENERATED"],
	"xhen" : [ "xhosa","AUTO GENERATED"],
	"bsen" : [ "bosnian","AUTO GENERATED"],
	"hren" : [ "croatian","AUTO GENERATED"],
	"sken" : [ "slovak","AUTO GENERATED"],
	"fien" : [ "finnish","AUTO GENERATED"],
	"isen" : [ "icelandic","AUTO GENERATED"],
	"noen" : [ "norwegian","AUTO GENERATED"],
	"then" : [ "thai","AUTO GENERATED"],
	"swen" : [ "swahili","AUTO GENERATED"],
	"paen" : [ "punjabi","AUTO GENERATED"],
	"kyen" : [ "kyrgyz","AUTO GENERATED"],
	"ceben" : [ "cebuano","AUTO GENERATED"],
	"iden" : [ "indonesian","AUTO GENERATED"],
	"kmen" : [ "khmer","AUTO GENERATED"],
	"ruen" : [ "russian","AUTO GENERATED"],
	"sien" : [ "sinhala","AUTO GENERATED"],
	"lven" : [ "latvian","AUTO GENERATED"],
	"psen" : [ "pashto","AUTO GENERATED"],
	"tlen" : [ "filipino","AUTO GENERATED"],
	"oren" : [ "odia","AUTO GENERATED"],
	"cyen" : [ "welsh","AUTO GENERATED"],
	"sven" : [ "swedish","AUTO GENERATED"],
	"huen" : [ "hungarian","AUTO GENERATED"],
	"knen" : [ "kannada","AUTO GENERATED"],
	"kken" : [ "kazakh","AUTO GENERATED"],
	"nyen" : [ "chichewa","AUTO GENERATED"],
	"laen" : [ "latin","AUTO GENERATED"],
	"guen" : [ "gujarati","AUTO GENERATED"],
	"suen" : [ "sundanese","AUTO GENERATED"],
	"fyen" : [ "frisian","AUTO GENERATED"],
	"mken" : [ "macedonian","AUTO GENERATED"],
	"yien" : [ "yiddish","AUTO GENERATED"],
	"slen" : [ "slovenian","AUTO GENERATED"],
	"myen" : [ "myanmar (burmese)","AUTO GENERATED"],
	"teen" : [ "telugu","AUTO GENERATED"],
	"bgen" : [ "bulgarian","AUTO GENERATED"],
	"mnen" : [ "mongolian","AUTO GENERATED"],
	"aren" : [ "arabic","AUTO GENERATED"],
	"zhcnen" : [ "chinese (simplified)","AUTO GENERATED"],
	"been" : [ "belarusian","AUTO GENERATED"],
	"eoen" : [ "esperanto","AUTO GENERATED"],
	"tren" : [ "turkish","AUTO GENERATED"],
	"euen" : [ "basque","AUTO GENERATED"],
	"amen" : [ "amharic","AUTO GENERATED"],
	"csen" : [ "czech","AUTO GENERATED"],
	"bnen" : [ "bengali","AUTO GENERATED"],
	"zuen" : [ "zulu","AUTO GENERATED"],
	"hyen" : [ "armenian","AUTO GENERATED"],
	"jaen" : [ "japanese","AUTO GENERATED"],
	"ugen" : [ "uyghur","AUTO GENERATED"],
	"deen" : [ "german","AUTO GENERATED"],
	"sqen" : [ "albanian","AUTO GENERATED"],
	"nlen" : [ "dutch","AUTO GENERATED"],
	"plen" : [ "polish","AUTO GENERATED"],
	"sden" : [ "sindhi","AUTO GENERATED"],
	"tgen" : [ "tajik","AUTO GENERATED"],
	"mien" : [ "maori","AUTO GENERATED"],
	"msen" : [ "malay","AUTO GENERATED"],
	"loen" : [ "lao","AUTO GENERATED"],
	"hten" : [ "haitian creole","AUTO GENERATED"],
	"faen" : [ "persian","AUTO GENERATED"],
	"vien" : [ "vietnamese","AUTO GENERATED"],
	"jwen" : [ "javanese","AUTO GENERATED"],
	"roen" : [ "romanian","AUTO GENERATED"],
	"sren" : [ "serbian","AUTO GENERATED"],
	"glen" : [ "galician","AUTO GENERATED"],
	"taen" : [ "tamil","AUTO GENERATED"],
	"smen" : [ "samoan","AUTO GENERATED"],
	"heen" : [ "hebrew","AUTO GENERATED"],
	"azen" : [ "azerbaijani","AUTO GENERATED"],
	"eten" : [ "estonian","AUTO GENERATED"],
	"hmnen" : [ "hmong","AUTO GENERATED"],
	"koen" : [ "korean","AUTO GENERATED"],
	"snen" : [ "shona","AUTO GENERATED"],
	"kuen" : [ "kurdish (kurmanji)","AUTO GENERATED"],
	"elen" : [ "greek","AUTO GENERATED"],
	"zhtwen" : [ "chinese (traditional)","AUTO GENERATED"],
	"daen" : [ "danish","AUTO GENERATED"],
	"uren" : [ "urdu","AUTO GENERATED"],
	"afen" : [ "afrikaans","AUTO GENERATED"],
	"kaen" : [ "georgian","AUTO GENERATED"]
}


enen = {
    "AUTHOR": "Krish Yadav",
    "VERSION": "1",
    "LANG": {"EN" : "EN"},
    "LANGUAGE": {"" : "ENGLISH"},
    "CT":".js",
    "EXTENSION":".",
    "SPECIAL_SYMBOLS":"+-*/% = &|^>< .",
    "NUMBERS": {"1234567890" : "1234567890"},
    "KEYWORDS" : {
        "abstract":"abstract",
        "arguments":"arguments",
        "await":"await",
        "boolean":"boolean",
        "break":"break",
        "byte":"byte",
        "case":"case",
        "catch":"catch",
        "char":"char",
        "class":"class",
        "const":"const",
        "continue":"continue",
        "debugger":"debugger",
        "default":"default",
        "delete":"delete",
        "do":"do",
        "double":"double",
        "else":"else",
        "enum":"enum",
        "eval":"eval",
        "export":"export",
        "extends":"extends",
        "false":"false",
        "final":"final",
        "finally":"finally",
        "float":"float",
        "for":"for",
        "function":"function",
        "goto":"goto",
        "if":"if",
        "implements":"implements",
        "import":"import",
        "in":"in",
        "instanceof":"instanceof",
        "int":"int",
        "interface":"interface",
        "let":"let",
        "long":"long",
        "native":"native",
        "new":"new",
        "null":"null",
        "package":"package",
        "private":"private",
        "protected":"protected",
        "public":"public",
        "return":"return",
        "short":"short",
        "static":"static",
        "super":"super*",
        "switch":"switch",
        "synchronized":"synchronized",
        "this":"this",
        "throw":"throw",
        "throws":"throws",
        "transient":"transient",
        "true":"true",
        "try":"try",
        "typeof":"typeof",
        "var":"var",
        "void":"void",
        "volatile":"volatile",
        "while":"while",
        "with":"with",
        "yield":"yield"
    },
    "FUNCTIONS" : {
        "display":"display",
        "Array":"Array",
        "Date":"Date",
        "eval":"eval",
        "function":"function",
        "hasOwnProperty":"hasOwnProperty",
        "Infinity":"Infinity",
        "isFinite":"isFinite",
        "isNaN":"isNaN",
        "isPrototypeOf":"isPrototypeOf",
        "length":"length",
        "Math":"Math",
        "NaN":"NaN",
        "name":"name",
        "Number":"Number",
        "Object":"Object",
        "prototype":"prototype",
        "String":"String",
        "toString":"toString",
        "undefined":"undefined",
        "valueOf":"valueOf",
        "print":"display",
        "input":"input",
        "clear":"clear",
        "int":"parseInt"
    },
    "ERRORS":{
        "EvalError":"EvalError",
        "RangeError":"RangeError",
        "ReferenceError":"ReferenceError",
        "SyntaxError":"SyntaxError",
        "TypeError":"TypeError",
        "URIError":"URIError",
        "AggregateError":"AggregateError"
    }
}

////////////////////////////////////////////////////////////////////////////////////////////

hien = {
    "AUTHOR": "Krish Yadav",
    "VERSION": "1",
    "LANG": {"HI" : "EN"},
    "LANGUAGE": {"HINDI" : "ENGLISH"},
    "CT":".js",
    "EXTENSION":".",
    "SPECIAL_SYMBOLS":"+-*/% = &|^>< .",
    "NUMBERS": {"१२३४५६७८९०" : "1234567890"},
    "KEYWORDS" : {
        "निराकार":"abstract",
        "बहस":"arguments",
        "इंतजार":"await",
        "बूलियन":"boolean",
        "टूटना":"break",
        "बाइट":"byte",
        "स्थिति":"case",
        "पकड़":"catch",
        "अक्षर":"char",
        "कक्षा":"class",
        "स्थिरांक":"const",
        "जारी":"continue",
        "डिबगर":"debugger",
        "चयनित":"default",
        "हटाना":"delete",
        "कर":"do",
        "दोगुना":"double",
        "अन्य":"else",
        "गिनना":"enum",
        "मूल्यांकन":"eval",
        "निर्यात":"export",
        "फैली":"extends",
        "असत्य":"false",
        "अंतिम":"final",
        "आखिरकार":"finally",
        "तैरना":"float",
        "दुहराओ":"for",
        "कृत्य":"function",
        "जाओ":"goto",
        "अगर":"if",
        "औजार":"implements",
        "औजार":"import",
        "में":"in",
        "का_उदाहरण":"instanceof",
        "पूर्णांक":"int",
        "अंतराफलक":"interface",
        "लश्कर":"let",
        "लंबा":"long",
        "देशी":"native",
        "नया":"new",
        "बातिल":"null",
        "पैकेज":"package",
        "निजी":"private",
        "संरक्षित":"protected",
        "सार्वजनिक":"public",
        "वापसी":"return",
        "कम":"short",
        "स्थिर":"static",
        "सुपर":"super",
        "स्विच":"switch",
        "सिंक्रनाइज़":"synchronized",
        "यह":"this",
        "फेंकना":"throw",
        "फेंकता":"throws",
        "क्षणिक":"transient",
        "सच":"true",
        "प्रयत्न":"try",
        "के-प्रकार":"typeof",
        "अस्थिर":"var",
        "शून्य":"void",
        "उदवायी":"volatile",
        "जबतक":"while",
        "साथ":"with",
        "उपज":"yield"
    },
    "FUNCTIONS" : {
        "सरणी":"Array",
        "तारीख":"Date",
        "मूल्यांकन":"eval",
        "समारोह":"function",
        "गुण":"hasOwnProperty",
        "अनन्तता":"Infinity",
        "परिमित":"isFinite",
        "isNaN":"isNaN",
        "":"isPrototypeOf",
        "लंबाई1":"length",
        "गणित":"Math",
        "नेन":"NaN",
        "नाम":"name",
        "संख्या":"Number",
        "वस्तु":"Object",
        "प्रोटोटाइप":"prototype",
        "तार":"String",
        "तार1":"toString",
        "undefined":"undefined",
        "कामूल्य":"valueOf",
        "दिखाए":"display",
        "डाल":"input",
        "पूर्णांक":"parseInt",
    },
    "ERRORS":{
        "EvalError":"मूल्यांकन त्रुटि",
        "RangeError":"सीमा त्रुटि",
        "ReferenceError":"संदर्भ त्रुटि",
        "SyntaxError":"वक्य रचना त्रुटि",
        "TypeError":"त्रुटि प्रकार",
        "URIError":"यूआरआई त्रुटि",
        "AggregateError":"कुल त्रुटि"
    }
}

maen = {
    "AUTHOR": "Yash Yadav",
    "VERSION": "1.0.0",
    "LANG": {"MA" : "EN"},
    "LANGUAGE": {"MARATHI" : "ENGLISH"},
    "CT":".js",
    "EXTENSION":".",
    "SPECIAL_SYMBOLS":"+-*/% = &|^>< .",
    "NUMBERS": {"१२३४५६७८९०" : "1234567890"},
    "KEYWORDS" : {
        "गोषवारा":"abstract",
        "वितर्क":"arguments",
        "थांब":"await",
        "बुलियन":"boolean",
        "विराम":"break",
        "बाइट":"byte",
        "केस":"case",
        "पकडण":"catch",
        "वर्ण":"char",
        "वर्ग":"class",
        "कॉन्स्टॅन":"const",
        "चालू":"continue",
        "डीबगर":"debugger",
        "डीफॉल्ट":"default",
        "हटवा":"delete",
        "करा":"do",
        "दुप्पट":"double",
        "अन्यथा":"else",
        "इनम":"enum",
        "मूल्यमापन":"eval",
        "निर्यात":"export",
        "वाढवत":"extends",
        "असत्य":"false",
        "अंतिम":"final",
        "शेवटी":"finally",
        "फ्लोट":"float",
        "पुन्हा":"for",
        "कार्य":"function",
        "जा":"goto",
        "ज़र ":"if",
        "अंमलबजावणी":"implements",
        "आयात":"import",
        "आत":"in",
        "उदाहरणार्थ":"instanceof",
        "पूर्णांक":"int",
        "इंटरफेस":"interface",
        "द्या":"let",
        "लांब":"long",
        "मुळ":"native",
        "नवीन":"new",
        "रिक्त":"null",
        "पॅकेज":"package",
        "खाजगी":"private",
        "संरक्षित":"protected",
        "सार्वजनिक":"public",
        "परत":"return",
        "लहान":"short",
        "स्थिर":"static",
        "उत्कृष्ट":"super*",
        "स्विच":"switch",
        "समक्रमित":"synchronized",
        "हे":"this",
        "फेकण":"throw",
        "फेकणे":"throws",
        "तात्पुरता":"transient",
        "सत्य":"true",
        "प्रयत्न":"try",
        "प्रकार":"typeof",
        "अनित्य":"var",
        "शून्य":"void",
        "अस्थिर":"volatile",
        "जेव्हा":"while",
        "सह":"with",
        "उत्पन्न":"yield"
    },
    "FUNCTIONS" : {
        "अरे":"Array",
        "तारीख":"Date",
        "मूल्यमापन१":"eval",
        "कार्य१":"function",
        "मालमत्ताहै":"hasOwnProperty",
        "अनंत":"Infinity",
        "मर्यादित":"isFinite",
        "एनएएनहै ":"isNaN",
        "नमुनाहै":"isPrototypeOf",
        "लांबी":"length",
        "गणित":"Math",
        "एनएएन":"NaN",
        "नाव":"name",
        "संख्या":"Number",
        "ऑब्जेक्ट":"Object",
        "नमुना":"prototype",
        "दोर":"String",
        "दोरको":"toString",
        "अपरिभाषित":"undefined",
        "मूल्य":"valueOf",
        "दाखवा":"display",
        "टाका":"input",
        "पूर्णांक":"parseInt",
    },
    "ERRORS":{
        "EvalError":"मूल्यमापनभूल",
        "RangeError":"श्रेणीचीचूक",
        "ReferenceError":"संदर्भचीचूक",
        "SyntaxError":"वाक्यरचनेचीचूक",
        "TypeError":"प्रकारचीचूक",
        "URIError":"युआरआईचीचूक",
        "AggregateError":"एकूणचीचूक"
    }
}
